name: Automated tests for Continuous integration
on: [push]
jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Vim-Vlsim"
        uses: actions/checkout@v4
      - name: "Install vim"
        run: sudo apt-get install vim
      - run: ls
      - run: tree
