name: Automated tests for Continuous integration
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Create runtime path"
        run:  mkdir runtime
      - name: "Checkout Vim-Vlsim"
        uses: actions/checkout@v4.1.1
        with:
          path: runtime/vim-unittest
      - name: "Install vim"
        run: sudo apt-get install vim
      - name: "Install Pathogen"
        run: mkdir -p ~/.vim/autoload ~/.vim/bundle && curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim && echo "execute pathogen#infect()" > ~/.vimrc
      - name: "Link to unittest in vim/bundle"
        run: ln -s runtime/vim-unittest ~/.vim/bundle/vim-unittest && ls -l ~/.vim/bundle && cat ~/.vimrc
      - name: "UnitTests"
        run: runtime/vim-unittest/bin/vunit runtime/vim-unittest/test-almost.vim
