name: Automated tests for Continuous integration
on: [push]
jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: "Create runtime path"
        run:  "mkdir runtime"
      - name: "Checkout Vim-Vlsim"
        uses: actions/checkout@v4.1.1
        with:
          path: runtime
      - name: "Install vim"
        run: sudo apt-get install vim
      - run: ls
      - run: tree
      - run: pwd
